name: aurasync
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ^3.32.1

dependencies:
  flutter:
    sdk: flutter

  flutter_acrylic: ^1.1.4
  flutter_modular: ^6.3.4
  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  aurasync_ui:
    path: ../aurasync_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
